# Generated by Django 4.0 on 2022-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=11)),
                ('department', models.CharField(max_length=11)),
                ('roll', models.CharField(max_length=11)),
            ],
        ),
    ]
