# Generated by Django 4.0 on 2022-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_studentinformation_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers_related', to='APP.TeacherInformation'),
        ),
    ]
