# Generated by Django 4.0 on 2022-01-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_remove_studentinformation_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='APP.teacherinformation'),
        ),
    ]
